loss_name: ctc
model_hparams:
  dropout: 0.5
  n_classes: 37
model_name: recognizer
optimizer_hparams:
  amsgrad: true
  betas: !!python/tuple
  - 0.9
  - 0.999
  lr: 0.001
  weight_decay: 0.01
optimizer_name: adamw
