IMG_WIDTH = 640
IMG_HEIGHT = 480
IMG_EXTENSIONS = (".jpg",)

TRAIN_FOLDER = "train"
VAL_FOLDER = "val"
POSITIVE_LABEL = 1
NEGATIVE_LABEL = 0

ANNOTATION_EXT = ".csv"
DATA_EXT = ".jpg"

IOU_POSITIVE = 0.7
IOU_NEGATIVE = 0.05

MAX_POSITIVE_SAMPLES = 20
MAX_NEGATIVE_SAMPLES = 15

DETECTION_INPUT_DIM = (100, 32)
RECOGNITION_INPUT_DIM = (100, 32)

TRAIN_VAL_SPLIT = 0.2

MAX_INFERENCE_SAMPLES = 2000

CLAHE_CLIP_LIMIT = 5
CLAHE_TILE_GRID_SIZE = (8, 8)

LP_TOPK = 10

LP_WIDTH_MIN = 60
LP_WIDTH_MAX = 285
LP_HEIGHT_MIN = 20
LP_HEIGHT_MAX = 135
LP_WIDTH_HEIGHT_RATIO_MIN = 1.0
LP_WIDTH_HEIGHT_RATIO_MAX = 6.5

LP_DISTORTION = 0.1
LP_ROT_ANGLE = 10

GAUSSIAN_BLUR_KSIZE = (3, 3)
GAUSSIAN_BLUR_SIGMAX = 0
