loss_name: bce
lr_scheduler_hparams:
  factor: 0.1
  min_lr: 1.0e-06
  mode: min
  patience: 4
lr_scheduler_name: reducelronplateau
model_hparams:
  dropout: 0.3
  n_classes: 1
model_name: detector
optimizer_hparams:
  betas: !!python/tuple
  - 0.9
  - 0.999
  lr: 0.001
  weight_decay: 0.0001
optimizer_name: adamw
