IMG_WIDTH = 640
IMG_HEIGHT = 480
IMG_EXTENSIONS = ('.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif')

TRAIN_PATH = "train"
VAL_PATH = "val"
POSITIVE_LABEL = 1
NEGATIVE_LABEL = 0

ANNOTATION_EXT = ".csv"
DATA_EXT = ".jpg"

IOU_POSITIVE = 0.7
IOU_NEGATIVE = 0.1

MAX_POSITIVE_SAMPLES = 30
MAX_NEGATIVE_SAMPLES = 30

RCNN_INPUT_DIM = (100, 100)

RANDOM_SEED = 42

TRAIN_VAL_SPLIT = 0.2

MAX_INFERENCE_SAMPLES = 100
