import os.path

IMG_WIDTH = 640
IMG_HEIGHT = 480
IMG_EXTENSIONS = ('.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif')

TRAIN_PATH = "train"
VAL_PATH = "val"
POSITIVE_LABEL = 1
NEGATIVE_LABEL = 0

ANNOTATION_EXT = ".csv"
DATA_EXT = ".jpg"

IOU_POSITIVE = 0.7
IOU_NEGATIVE = 0.2

MAX_POSITIVE_SAMPLES = 5
MAX_NEGATIVE_SAMPLES = 20

RCNN_INPUT_DIM = (120, 120)

RANDOM_SEED = 42

TRAIN_VAL_SPLIT = 0.2

MAX_INFERENCE_SAMPLES = 100

OD_PL_PATH = "od"
OD_PL_MODELS_PATH = os.path.join(OD_PL_PATH, "models")

CLAHE_CLIP_LIMIT = 15
CLAHE_TILE_GRID_SIZE = (25, 25)

RANDOM_ROTATION = 15
